on: push

jobs:
  test-infisical:
    runs-on: ubuntu-24.04
    steps:
      - name: infisical
        id: infisical
        uses: MPDHC/infisical@v2
        with:
          domain: ${{ secrets.INFISICAL_DOMAIN }}
          token: ${{ secrets.INFISICAL_SERVICE_TOKEN }}
          project-id: ${{ secrets.INFISICAL_PROJECT_ID }}
          recursive: true

      - name: Save secrets into .env
        run: |
          echo "AUTHENTIK_CLIENT_ID=${{ steps.infisical.outputs.AUTHENTIK_CLIENT_ID }}"
          echo "AUTHENTIK_CLIENT_SECRET=${{ steps.infisical.outputs.AUTHENTIK_CLIENT_SECRET }}"
